/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "debugcb.h"
#include "debugif.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mmr_win (void)
{
  GtkWidget *mmr_win;
  GtkWidget *vbox1;
  GtkWidget *mmr_notebook;
  GtkWidget *empty_notebook_page;
  GtkWidget *label16;
  GtkWidget *hbuttonbox1;
  GtkWidget *mmr_close;

  mmr_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mmr_win), _("lxDream! - Memory-Mapped Registers"));
  gtk_window_set_default_size (GTK_WINDOW (mmr_win), 600, 600);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mmr_win), vbox1);

  mmr_notebook = gtk_notebook_new ();
  gtk_widget_show (mmr_notebook);
  gtk_box_pack_start (GTK_BOX (vbox1), mmr_notebook, TRUE, TRUE, 0);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (mmr_notebook), GTK_POS_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (mmr_notebook), empty_notebook_page);

  label16 = gtk_label_new (_("label16"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (mmr_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (mmr_notebook), 0), label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_CENTER);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  mmr_close = gtk_button_new_with_mnemonic (_("Close"));
  gtk_widget_show (mmr_close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), mmr_close);
  GTK_WIDGET_SET_FLAGS (mmr_close, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) mmr_win, "delete_event",
                    G_CALLBACK (on_mmr_win_delete_event),
                    NULL);
  g_signal_connect ((gpointer) mmr_close, "clicked",
                    G_CALLBACK (on_mmr_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mmr_win, mmr_win, "mmr_win");
  GLADE_HOOKUP_OBJECT (mmr_win, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mmr_win, mmr_notebook, "mmr_notebook");
  GLADE_HOOKUP_OBJECT (mmr_win, label16, "label16");
  GLADE_HOOKUP_OBJECT (mmr_win, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (mmr_win, mmr_close, "mmr_close");

  return mmr_win;
}

GtkWidget*
create_dump_win (void)
{
  GtkWidget *dump_win;
  GtkWidget *vbox3;
  GtkWidget *hbox2;
  GtkWidget *label34;
  GtkWidget *dump_from;
  GtkWidget *label35;
  GtkWidget *dump_to;
  GtkWidget *dump_view_button;
  GtkWidget *label36;
  GtkWidget *scrolledwindow9;
  GtkWidget *dump_text;

  dump_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (dump_win), _("Memory dump"));

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (dump_win), vbox3);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox2, FALSE, TRUE, 3);

  label34 = gtk_label_new (_(" From "));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox2), label34, FALSE, FALSE, 0);

  dump_from = gtk_entry_new ();
  gtk_widget_show (dump_from);
  gtk_box_pack_start (GTK_BOX (hbox2), dump_from, FALSE, TRUE, 0);

  label35 = gtk_label_new (_(" To "));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox2), label35, FALSE, FALSE, 0);

  dump_to = gtk_entry_new ();
  gtk_widget_show (dump_to);
  gtk_box_pack_start (GTK_BOX (hbox2), dump_to, FALSE, TRUE, 0);

  dump_view_button = gtk_button_new_with_mnemonic (_("View"));
  gtk_widget_show (dump_view_button);
  gtk_box_pack_start (GTK_BOX (hbox2), dump_view_button, FALSE, FALSE, 0);

  label36 = gtk_label_new (_("   "));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox2), label36, TRUE, TRUE, 0);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow9, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_SHADOW_IN);

  dump_text = gtk_text_view_new ();
  gtk_widget_show (dump_text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), dump_text);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dump_win, dump_win, "dump_win");
  GLADE_HOOKUP_OBJECT (dump_win, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (dump_win, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (dump_win, label34, "label34");
  GLADE_HOOKUP_OBJECT (dump_win, dump_from, "dump_from");
  GLADE_HOOKUP_OBJECT (dump_win, label35, "label35");
  GLADE_HOOKUP_OBJECT (dump_win, dump_to, "dump_to");
  GLADE_HOOKUP_OBJECT (dump_win, dump_view_button, "dump_view_button");
  GLADE_HOOKUP_OBJECT (dump_win, label36, "label36");
  GLADE_HOOKUP_OBJECT (dump_win, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (dump_win, dump_text, "dump_text");

  return dump_win;
}

