/**
 * $Id: debugcb.c,v 1.3 2007-10-21 05:21:35 nkeynes Exp $
 *
 * All GTK callbacks go here (stubs are autogenerated by Glade)
 *
 * Copyright (c) 2005 Nathan Keynes.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include <gnome.h>

#include "config.h"
#include "gui/debugcb.h"
#include "gui/debugif.h"
#include "gui/gtkui.h"
#include "gdrom/gdrom.h"
#include "mem.h"
#include "mmio.h"
#include "dreamcast.h"
#include "loader.h"
#include "pvr2/pvr2.h"

void on_trace_button_toggled           (GtkToggleButton *button,
					gpointer user_data)
{
    struct mmio_region *io_rgn = (struct mmio_region *)user_data;
    gboolean isActive = gtk_toggle_button_get_active(button);
    if( io_rgn != NULL ) {
	io_rgn->trace_flag = isActive ? 1 : 0;
    }
}


gboolean
on_mmr_win_delete_event                (GtkWidget       *widget,
                                        GdkEvent        *event,
                                        gpointer         user_data)
{
    mmr_close_win();
    return TRUE;
}


void
on_mmr_close_clicked                   (GtkButton       *button,
                                        gpointer         user_data)
{
    mmr_close_win();
}
