/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_debug_win (void);
GtkWidget* create_mmr_win (void);
GtkWidget* create_about_win (void);
GtkWidget* create_dump_win (void);
GtkWidget* create_watch_win (void);
