/**
 * This file is automatically generated - do not edit
 */

const char *glsl_vertex_shader_src = "// Standard PVR2 vertex shader\n\
\n\
void main()\n\
{\n\
	gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\n\
}\n\
";

const char *glsl_fragment_shader_src = "// Standard PVR2 fragment shader\n\
\n\
void main()\n\
{\n\
	gl_FragColor = gl_Color;\n\
}";

