Document: lxdream
Title: Debian lxdream Manual
Author: <insert document author here>
Abstract: This manual describes what lxdream is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxdream/lxdream.sgml.gz

Format: postscript
Files: /usr/share/doc/lxdream/lxdream.ps.gz

Format: text
Files: /usr/share/doc/lxdream/lxdream.text.gz

Format: HTML
Index: /usr/share/doc/lxdream/html/index.html
Files: /usr/share/doc/lxdream/html/*.html

  
