/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "gui/gui.h"
#include "dream.h"
#include "dreamcast.h"

int
main (int argc, char *argv[])
{
#ifdef ENABLE_NLS
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);
#endif
  dreamcast_init();
  gnome_init ("dreamon", VERSION, argc, argv);
  dreamcast_register_module( &gtk_gui_module );
  video_open();
  // mem_new_watch( 0x0C204818, 0x0C204830, WATCH_WRITE );
  
  emit( main_debug, EMIT_INFO, -1, "DreamOn! ready..." );

  gtk_main ();
  return 0;
}

